version: '3.8'

services:
  api:
    build: .
    container_name: football_predictor_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://football_user:football_pass@db:5432/football_predictor
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - football_net

  db:
    image: postgres:15-alpine
    container_name: football_predictor_db
    environment:
      - POSTGRES_USER=football_user
      - POSTGRES_PASSWORD=football_pass
      - POSTGRES_DB=football_predictor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - football_net

  redis:
    image: redis:7-alpine
    container_name: football_predictor_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - football_net

  celery_worker:
    build: .
    container_name: football_predictor_worker
    command: celery -A src.tasks.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://football_user:football_pass@db:5432/football_predictor
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - football_net

  celery_beat:
    build: .
    container_name: football_predictor_beat
    command: celery -A src.tasks.celery_app beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://football_user:football_pass@db:5432/football_predictor
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - football_net

volumes:
  postgres_data:
  redis_data:

networks:
  football_net:
    driver: bridge
